function main_gui
    fig = figure('Name', 'Team 8 Image Processing Project', ...
        'Position', [100 100 900 600], ...
        'Color', [0.96 0.96 0.96], ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none');
    
    appData = struct();
    appData.OriginalAxes = [];
    appData.ProcessedAxes = [];
    appData.OriginalImage = [];
    appData.ProcessedImage = [];
    setappdata(fig, 'AppData', appData);
    
    leftPanel = uipanel('Parent', fig, ...
        'Title', 'Controls', ...
        'FontWeight', 'bold', ...
        'FontSize', 12, ...
        'BackgroundColor', [0.96 0.96 0.96], ...
        'Position', [0.02 0.02 0.22 0.96]);
    
    rightPanel = uipanel('Parent', fig, ...
        'Title', 'Image Views', ...
        'FontWeight', 'bold', ...
        'FontSize', 12, ...
        'BackgroundColor', [0.96 0.96 0.96], ...
        'Position', [0.25 0.02 0.73 0.96]);
    
    buttonHeight = 0.09;
    spacing = 0.01;
    currentY = 0.88;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Load Image', ...
        'FontWeight', 'bold', ...
        'FontSize', 11, ...
        'BackgroundColor', [0.20 0.45 0.80], ...
        'ForegroundColor', [1 1 1], ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onLoadImage(src, fig));
    
    currentY = currentY - buttonHeight - spacing;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Canny Edge', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onCannyEdge(src, fig));
    
    currentY = currentY - buttonHeight - spacing;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Diff of Gaussians', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onDiffOfGaussians(src, fig));
    
    currentY = currentY - buttonHeight - spacing;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Add Salt & Pepper', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onAddSaltPepper(src, fig));
    
    currentY = currentY - buttonHeight - spacing;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Add Gaussian Noise', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onAddGaussianNoise(src, fig));
    
    currentY = currentY - buttonHeight - spacing;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Remove Noise', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onRemoveNoise(src, fig));
    
    currentY = currentY - buttonHeight - spacing;
    
    uicontrol('Parent', leftPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Hist Equalization', ...
        'FontSize', 11, ...
        'Units', 'normalized', ...
        'Position', [0.05 currentY 0.9 buttonHeight], ...
        'Callback', @(src, event) gui_logic.onHistEqualization(src, fig));
    
    axesHeight = 0.45;
    axesSpacing = 0.05;
    
    axOriginal = axes('Parent', rightPanel, ...
        'Units', 'normalized', ...
        'Position', [0.05 0.52 0.9 axesHeight], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    title(axOriginal, 'Original Image', 'FontSize', 12, 'FontWeight', 'bold');
    
    axProcessed = axes('Parent', rightPanel, ...
        'Units', 'normalized', ...
        'Position', [0.05 0.02 0.9 axesHeight], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    title(axProcessed, 'Processed Image', 'FontSize', 12, 'FontWeight', 'bold');
    
    appData = getappdata(fig, 'AppData');
    appData.OriginalAxes = axOriginal;
    appData.ProcessedAxes = axProcessed;
    setappdata(fig, 'AppData', appData);
    
    gui_logic.setupPaths();
end